/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interacaoComUsuario.telas;

/**
 *
 * @author Thiago
 */
public class TelaLivro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLivro
     */
    public TelaLivro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_TelaLivro = new javax.swing.JPanel();
        jPanel_Cabecalho = new javax.swing.JPanel();
        jLabel_NomePrograma = new javax.swing.JLabel();
        jLabel_IconePrograma1 = new javax.swing.JLabel();
        jLabel_Data = new javax.swing.JLabel();
        jLabel_Hora = new javax.swing.JLabel();
        jButton_BotaoTelaUsuario = new javax.swing.JButton();
        jButton_BloquearLivro = new javax.swing.JButton();
        jButton_RemoverLivro = new javax.swing.JButton();
        jPanel_Info = new javax.swing.JPanel();
        jLabel_TituloLivro = new javax.swing.JLabel();
        jLabel_AutorLivro = new javax.swing.JLabel();
        jLabel_DataDePublicaçãoLivro = new javax.swing.JLabel();
        jLabel_EditoraLivro = new javax.swing.JLabel();
        jLabel_IDLivro = new javax.swing.JLabel();
        jLabel_QuantidadeEstoqueLivro = new javax.swing.JLabel();
        jLabel_LocalizaçãoLivro = new javax.swing.JLabel();
        jLabel_IdiomaLivro = new javax.swing.JLabel();
        jLabel_AvaliarLivro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_Cabecalho.setBackground(new java.awt.Color(153, 204, 255));

        jLabel_NomePrograma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NomePrograma.setText("NOME DO PROGRAMA");

        jLabel_IconePrograma1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_IconePrograma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interacaoComUsuario/img/Webp.net-resizeimage.png"))); // NOI18N

        jLabel_Data.setText("00/00/0000");

        jLabel_Hora.setText("00:00");

        jButton_BotaoTelaUsuario.setText("Tela do Usuário");

        jButton_BloquearLivro.setText("Bloquear Livro");
        jButton_BloquearLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BloquearLivroActionPerformed(evt);
            }
        });

        jButton_RemoverLivro.setText("Remover Livro");
        jButton_RemoverLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoverLivroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_CabecalhoLayout = new javax.swing.GroupLayout(jPanel_Cabecalho);
        jPanel_Cabecalho.setLayout(jPanel_CabecalhoLayout);
        jPanel_CabecalhoLayout.setHorizontalGroup(
            jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_IconePrograma1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                        .addComponent(jLabel_NomePrograma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_RemoverLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_BloquearLivro)
                        .addGap(10, 10, 10)
                        .addComponent(jButton_BotaoTelaUsuario))
                    .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel_Hora)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Data)))
                .addContainerGap())
        );
        jPanel_CabecalhoLayout.setVerticalGroup(
            jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                        .addGroup(jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Hora)
                            .addComponent(jLabel_Data))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_BotaoTelaUsuario)
                            .addComponent(jButton_BloquearLivro)
                            .addComponent(jButton_RemoverLivro)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_CabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_IconePrograma1)
                        .addGroup(jPanel_CabecalhoLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel_NomePrograma))))
                .addContainerGap())
        );

        jLabel_TituloLivro.setText("Nome: NOME DO LIVRO");

        jLabel_AutorLivro.setText("Autor: AUTOR DO LIVRO");

        jLabel_DataDePublicaçãoLivro.setText("Data de publicação: **/**/****");

        jLabel_EditoraLivro.setText("Editora: EDITORA DO LIVRO");

        jLabel_IDLivro.setText("ID: ID DO LIVRO");

        jLabel_QuantidadeEstoqueLivro.setText("Quantidade em Estoque: QUANTIDADE DO LIVRO EM ESTOQUE");

        jLabel_LocalizaçãoLivro.setText("Localização na Biblioteca: LOCALIZAÇÃO DO LIVRO NA BIBLIOTECA");

        jLabel_IdiomaLivro.setText("Idioma: IDIOMA DO LIVRO");

        jLabel_AvaliarLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_AvaliarLivro.setText("Avalie o livro: * * * * *");

        javax.swing.GroupLayout jPanel_InfoLayout = new javax.swing.GroupLayout(jPanel_Info);
        jPanel_Info.setLayout(jPanel_InfoLayout);
        jPanel_InfoLayout.setHorizontalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_TituloLivro)
                    .addComponent(jLabel_AutorLivro)
                    .addComponent(jLabel_EditoraLivro)
                    .addComponent(jLabel_DataDePublicaçãoLivro))
                .addGap(30, 30, 30)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_IdiomaLivro)
                    .addComponent(jLabel_LocalizaçãoLivro)
                    .addComponent(jLabel_QuantidadeEstoqueLivro)
                    .addComponent(jLabel_IDLivro))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_AvaliarLivro)
                .addContainerGap())
        );
        jPanel_InfoLayout.setVerticalGroup(
            jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_AvaliarLivro)
                .addGap(5, 5, 5)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TituloLivro)
                    .addComponent(jLabel_IDLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AutorLivro)
                    .addComponent(jLabel_QuantidadeEstoqueLivro))
                .addGap(16, 16, 16)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_DataDePublicaçãoLivro)
                    .addComponent(jLabel_LocalizaçãoLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_EditoraLivro)
                    .addComponent(jLabel_IdiomaLivro))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_TelaLivroLayout = new javax.swing.GroupLayout(jPanel_TelaLivro);
        jPanel_TelaLivro.setLayout(jPanel_TelaLivroLayout);
        jPanel_TelaLivroLayout.setHorizontalGroup(
            jPanel_TelaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TelaLivroLayout.createSequentialGroup()
                .addComponent(jPanel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addComponent(jPanel_Cabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_TelaLivroLayout.setVerticalGroup(
            jPanel_TelaLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TelaLivroLayout.createSequentialGroup()
                .addComponent(jPanel_Cabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TelaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_TelaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BloquearLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BloquearLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_BloquearLivroActionPerformed

    private void jButton_RemoverLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoverLivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RemoverLivroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_BloquearLivro;
    private javax.swing.JButton jButton_BotaoTelaUsuario;
    private javax.swing.JButton jButton_RemoverLivro;
    private javax.swing.JLabel jLabel_AutorLivro;
    private javax.swing.JLabel jLabel_AvaliarLivro;
    private javax.swing.JLabel jLabel_Data;
    private javax.swing.JLabel jLabel_DataDePublicaçãoLivro;
    private javax.swing.JLabel jLabel_EditoraLivro;
    private javax.swing.JLabel jLabel_Hora;
    private javax.swing.JLabel jLabel_IDLivro;
    private javax.swing.JLabel jLabel_IconePrograma1;
    private javax.swing.JLabel jLabel_IdiomaLivro;
    private javax.swing.JLabel jLabel_LocalizaçãoLivro;
    private javax.swing.JLabel jLabel_NomePrograma;
    private javax.swing.JLabel jLabel_QuantidadeEstoqueLivro;
    private javax.swing.JLabel jLabel_TituloLivro;
    private javax.swing.JPanel jPanel_Cabecalho;
    private javax.swing.JPanel jPanel_Info;
    private javax.swing.JPanel jPanel_TelaLivro;
    // End of variables declaration//GEN-END:variables
}
